apiVersion: v1
kind: Service
metadata:
  name: nginxi-svc
  namespace: default
spec:
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  clusterIP: 10.11.10.15
